Name:           ros-indigo-object-recognition-transparent-objects
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS object_recognition_transparent_objects package

Group:          Development/Libraries
License:        BSD
URL:            http://wg-perception.github.io/transparent_objects
Source0:        %{name}-%{version}.tar.gz

Requires:       openni-devel
Requires:       ros-indigo-ecto
Requires:       ros-indigo-ecto-opencv
Requires:       ros-indigo-object-recognition-core
Requires:       ros-indigo-pcl-ros
BuildRequires:  openni-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecto
BuildRequires:  ros-indigo-object-recognition-core
BuildRequires:  ros-indigo-pcl-ros

%description
A technique to recognize and estimate poses of transparent objects

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jul 27 2014 Ilya Lysenkov <ilya.lysenkov@itseez.com> - 0.4.0-0
- Autogenerated by Bloom

